apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 4499       # Service port
      targetPort: 4499 # Container port
      nodePort: 30080  # Fixed NodePort (optional, 30000-32767)
  type: NodePort
